apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-etcd01
  template:
    metadata:
      labels:
        app: centos-etcd01 
    spec:
      containers:
      - name: centos-etcd01 
        image: reg.xiaodonghub.com/library/centos_etcd:0.1
        ports:
        - containerPort: 22
        volumeMounts:
        - name: etcdconfig
          mountPath: /root/etcd
      volumes:
      - name: etcdconfig
        hostPath:
          path: /root/etcd/config
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd02-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-etcd02
  template:
    metadata:
      labels:
        app: centos-etcd02
    spec:
      containers:
      - name: centos-etcd02
        image: reg.xiaodonghub.com/library/centos_etcd:0.1
        ports:
        - containerPort: 22
        volumeMounts:
        - name: etcdconfig
          mountPath: /root/etcd
      volumes:
      - name: etcdconfig
        hostPath:
          path: /root/etcd/config
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd03-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-etcd03
  template:
    metadata:
      labels:
        app: centos-etcd03
    spec:
      containers:
      - name: centos-etcd03
        image: reg.xiaodonghub.com/library/centos_etcd:0.1
        ports:
        - containerPort: 22
        volumeMounts:
        - name: etcdconfig
          mountPath: /root/etcd
      volumes:
      - name: etcdconfig
        hostPath:
          path: /root/etcd/config
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: etcd01-svc
spec:
  type: NodePort
  selector:
    app: centos-etcd01
  ports:
    - protocol: TCP
      port: 8122
      targetPort: 22
      nodePort: 30122
---
apiVersion: v1
kind: Service
metadata:
  name: etcd02-svc
spec:
  type: NodePort
  selector:
    app: centos-etcd02
  ports:
    - protocol: TCP
      port: 8222
      targetPort: 22
      nodePort: 30222
---
apiVersion: v1
kind: Service
metadata:
  name: etcd03-svc
spec:
  type: NodePort
  selector:
    app: centos-etcd03
  ports:
    - protocol: TCP
      port: 8322
      targetPort: 22
      nodePort: 30322
