apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-sshd
  template:
    metadata:
      labels:
        app: centos-sshd 
    spec:
      containers:
      - name: centos-sshd 
        image: reg.xiaodonghub.com/library/centos_sshd_tools:0.1
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  type: NodePort
  selector:
    app: centos-sshd
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 22
      nodePort: 30022
